version: '3.8'
services:
  devops:
    image: hanvitha/devops
    ports:
      - "81:80"
    deploy:
      replicas: 3
  aws:
    image: hanvitha/aws
    ports:
      - "82:80"
    deploy:
      replicas: 3
  course:
    image: hanvitha/java
    ports:
      - "83:80"
    deploy:
      replicas: 3
  courses:
    image: hanvitha/python
    ports:
      - "84:80"
    deploy:
      replicas: 3


